### ISSUE TITLE
notion config get not working?

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#212]
When using latest master (have not tested last tagged version), running `notion config get node.default` returns nothing.

Contents of `$NOTION_HOME/catalog.toml`:

```toml
[node]
default = '6.15.0'
versions = [
    '6.15.0',
    '11.3.0',
]

[yarn]
default = '1.12.3'
versions = ['1.12.3']

```

I identified this by looking into why `$NOTION_NODE` and `$NOTION_YARN` were not being defined properly.
